{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  labels:
    {{- include "oficina-api.labels" . | nindent 4 }}
# AWS Academy: sem IRSA. Os pods usam as permissoes da LabRole anexada ao node
# (via instance metadata) para publicar na fila SQS de notificacoes.
automountServiceAccountToken: false
{{- end }}
