apiVersion: v1
kind: Secret
metadata:
  name: oficina-api-secret
  namespace: oficina-api
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL29maWNpbmE6c3Vic3RpdHVhLXNlbmhhQHBvc3RncmVzLXNlcnZpY2U6NTQzMi9vZmljaW5hX2Ri
  JWT_SECRET: c3Vic3RpdHVhLXBvci11bS1zZWdyZWRvLWZvcnRl
  JWT_EXPIRATION: MTVt
  JWT_REFRESH_SECRET: c3Vic3RpdHVhLXBvci1vdXRyby1zZWdyZWRvLWZvcnRl
  JWT_REFRESH_EXPIRATION: N2Q=
  ADMIN_SEED_PASSWORD: c3Vic3RpdHVhLWFkbWluLXNlZWQtcGFzc3dvcmQ=
  ORCAMENTO_WEBHOOK_TOKEN: c3Vic3RpdHVhLXBvci10b2tlbi13ZWJob29r
